# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A57IhaQftNHQhGdaT13zeE1YmuWQ4PhH
"""

import numpy as np
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

# These might be helpful:
from datetime import datetime, timedelta

pd.options.display.float_format = '{:,.2f}'.format

df_data = pd.read_csv('mission_launches.csv')

df_data.shape

df_data.columns

df_data.isnull().values.any()

df_data.duplicated().values.any()

df_data.sample(5)

df_data = df_data.dropna()

new_df = df_data.groupby(["Organisation"]).count()['Mission_Status']

new_df.values

bar = px.bar(
    x = new_df.values, 
    y = new_df.index,
    orientation='h',
    title = "Number of Space launches by Organisation"
)

bar.update_layout(xaxis_title="Number of lanuches" , yaxis_title="Organisations")

bar.show()

df_data.sample(5)

print(f'Number of active rockets is: {df_data[df_data.Rocket_Status == "StatusActive"].count()}')
print(f'Number of decomissioned rockets is: {df_data[df_data.Rocket_Status == "StatusRetired"].count()}')

df_data.groupby("Rocket_Status").count()['Detail']

df_data.groupby("Mission_Status").count()['Detail']

df_data.Price.fillna(0, inplace=True)

df_data = df_data.sort_values(by = "Price", ascending=True)

hist = px.bar(
    df_data,
    x = "Price",
)
hist.show()



